### ISSUE TITLE
命主、庙旺得利平陷计算结果有问题

### ISSUE THREAD

**Issue by longting** [airicyu/Fortel#1]
用https://www.china95.net/paipan/ziwei/ 测试结果用`2019-4-24 2:00:00`测试命主是 文曲，但是本代码测试结果是命主：巨門。  
同样用各种紫微排盘的结果命主都是文曲，还有对应的庙旺得利平陷`majorStarEnergy` 有些地方对应有问题。

**Comment by airicyu** [comment]
hi @longting ,
我通常是用王亭之的網站kankanwoo為標準去驟證的。
http://www.kankanwoo.com/?page_id=100
kankanwoo的網站用2019-4-24 2:00:00測試其命主也是巨門。

入廟﹑旺﹑平﹑陷的評級問題，你能否給我一些測試例子數據可以讓我查看一下？

**Comment by airicyu** [comment]
入廟﹑旺﹑平﹑陷的評級設定，我是跟據這張notes而定的:

https://i.postimg.cc/1R67VYh4/dousou-12basic.jpg

**Comment by longting** [comment]
![image](https://user-images.githubusercontent.com/5129611/56861221-7d226c00-69d1-11e9-90cf-5dfb495c7c30.png)

![image](https://user-images.githubusercontent.com/5129611/56861267-d9858b80-69d1-11e9-9ebe-6f1021948680.png)

上面是我测的结果，其他网站上测试的命主也是文曲

**Comment by longting** [comment]
仔细对比每个宫位里面的内容，很多地方都不一样
![image](https://user-images.githubusercontent.com/5129611/56861517-2a967f00-69d4-11e9-9eeb-dbb8c094ad4b.png)

**Comment by airicyu** [comment]
@longting 不同的派別起盤的方法不盡相同，所以才會有不同的結果。
安"命主"的方法，一般派別是以命宮宮位地支而安(卯=>文曲)，而中州派別是以年支而安(亥=>巨門)。

口訣:「子屬貪狼丑亥門，寅戌生人屬祿存，卯酉屬文巳未武，辰申廉宿午破軍。」

p.s. 我會在首頁的readme中加上remark說明這個library是以中州派的方法起盤。

**Comment by longting** [comment]
@airicyu 能否新增一般派排盘方式。可以加一个选项，选择一般派和中州派任意排盘。

**Comment by airicyu** [comment]
@longting 其他各門各派(不只一種)的起盤方法也是不盡相同啊

**Comment by airicyu** [comment]
由於查找了這並不是bug, 我且先close了這個issue吧
