### ISSUE TITLE
如何计算大运和流年

### ISSUE THREAD

**Issue by hustxjs** [airicyu/Fortel#8]
请问如何计算大运和流年的盘，能加到test吗

**Comment by airicyu** [comment]
https://github.com/airicyu/Fortel/blob/master/fortelcore/src/test/java/com/airic/fortel/core/destiny/DestinyTest.java

@hustxjs 你看這個file吧，裡面就是在算大運(十年)和流年的資訊。

```
Map<RuntimeCategory, RuntimeInfo> runtimeInfoMap = RuntimeInfo.getRuntimeInfoMap(destiny,
				new Lunar(2017, 6, 24, false));

RuntimeInfo tenYearRuntimeInfo = runtimeInfoMap.get(RuntimeCategory.TEN_YEAR);
```

tenYearRuntimeInfo.getRuntimeDestinyTempleGround() <---- 大運命宮的地支

tenYearRuntimeInfo.getRuntimeMinorStarsMap().get(MinorStar.XXXX) <--- 大運飛曜的地支

tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.XXXX) <--- 大運四化的星

流年的也是類似，那file裡都有例子可看看。

**Comment by hustxjs** [comment]
> https://github.com/airicyu/Fortel/blob/master/fortelcore/src/test/java/com/airic/fortel/core/destiny/DestinyTest.java
> 
> @hustxjs 你看這個file吧，裡面就是在算大運(十年)和流年的資訊。
> 
> ```
> Map<RuntimeCategory, RuntimeInfo> runtimeInfoMap = RuntimeInfo.getRuntimeInfoMap(destiny,
> 				new Lunar(2017, 6, 24, false));
> 
> RuntimeInfo tenYearRuntimeInfo = runtimeInfoMap.get(RuntimeCategory.TEN_YEAR);
> ```
> 
> tenYearRuntimeInfo.getRuntimeDestinyTempleGround() <---- 大運命宮的地支
> 
> tenYearRuntimeInfo.getRuntimeMinorStarsMap().get(MinorStar.XXXX) <--- 大運飛曜的地支
> 
> tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.XXXX) <--- 大運四化的星
> 
> 流年的也是類似，那file裡都有例子可看看。

好的，我看到了，感谢！
但是个问题，以代码中的案例：
Config initConfig = new Config(ConfigType.SKY, Sex.M, 1952, 12, 15, false, GroundTime.getByName("寅").get());
这是一个阴历时间，我用文墨天机排盘，得到左辅化科，但代码给出的是:天府化科，为什么不一样呢

**Comment by airicyu** [comment]
![image](https://github.com/airicyu/Fortel/assets/10323163/c249ed22-4c3c-4669-bf77-e6bf9f238d74)
這樣嗎?
我這個library應該是會計算結果是天府化科是先天的, 十年紫微化科, 流年天機化科

**Comment by airicyu** [comment]
我剛剛在王亭之的網站對過:
https://www.kankanwoo.com/?page_id=100
它也是先天天府化科的, 十年流年它網站沒法看我就驗證不到了.

![image](https://github.com/airicyu/Fortel/assets/10323163/63c7b672-4678-4a02-b720-f6b1eba0579b)

當中如果文墨天機的結果不同, 有可能是不同派別有些計算方式不同吧。(這個我不確定因為不懂其他派別)
我的那套計算方法是跟王亭之notes去寫的, 所以與王亭之網站的結果一樣。

**Comment by hustxjs** [comment]
好的，感谢解答！
