### ISSUE TITLE
请问如何计算宫位四化

### ISSUE THREAD

**Issue by hustxjs** [airicyu/Fortel#9]

**Comment by airicyu** [comment]
四化所代表的Enum:
https://github.com/airicyu/Fortel/blob/master/fortelcore/src/main/java/com/airic/fortel/core/model/StarReaction.java

求先天的四化:
Destiny class中有個method:
`public Star getReactionStar(StarReaction starReaction) `
用四化enum作param就能求得四化的星

流曜的四化:
參看這個test, https://github.com/airicyu/Fortel/blob/master/fortelcore/src/test/java/com/airic/fortel/core/destiny/DestinyTest.java

下面的例子是求十年大運的四化
```
Map<RuntimeCategory, RuntimeInfo> runtimeInfoMap = RuntimeInfo.getRuntimeInfoMap(destiny, new Lunar(2017, 6, 24, false));
RuntimeInfo tenYearRuntimeInfo = runtimeInfoMap.get(RuntimeCategory.TEN_YEAR);

Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_TREASURE),
				MajorStar.MAJOR_STAR_COUNSELLOR);
Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_POWER),
				MajorStar.MAJOR_STAR_LAW);
Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_POSITION),
				MajorStar.MAJOR_STAR_EMPEROR);
Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_PROBLEM),
				MajorStar.MAJOR_STAR_MOON);
```

**Comment by hustxjs** [comment]
> 四化所代表的Enum: https://github.com/airicyu/Fortel/blob/master/fortelcore/src/main/java/com/airic/fortel/core/model/StarReaction.java
> 
> 求先天的四化: Destiny class中有個method: `public Star getReactionStar(StarReaction starReaction) ` 用四化enum作param就能求得四化的星
> 
> 流曜的四化: 參看這個test, https://github.com/airicyu/Fortel/blob/master/fortelcore/src/test/java/com/airic/fortel/core/destiny/DestinyTest.java
> 
> 下面的例子是求十年大運的四化
> 
> ```
> Map<RuntimeCategory, RuntimeInfo> runtimeInfoMap = RuntimeInfo.getRuntimeInfoMap(destiny, new Lunar(2017, 6, 24, false));
> RuntimeInfo tenYearRuntimeInfo = runtimeInfoMap.get(RuntimeCategory.TEN_YEAR);
> 
> Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_TREASURE),
> 				MajorStar.MAJOR_STAR_COUNSELLOR);
> Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_POWER),
> 				MajorStar.MAJOR_STAR_LAW);
> Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_POSITION),
> 				MajorStar.MAJOR_STAR_EMPEROR);
> Assertions.assertEquals(tenYearRuntimeInfo.getRuntimeStarReactionMap().get(StarReaction.STAR_TO_PROBLEM),
> 				MajorStar.MAJOR_STAR_MOON);
> ```

这些test挺好的，我都试过了。但我想要的是宫干四化，比如夫妻宫是甲干，四化的结果，这个有吗？

**Comment by airicyu** [comment]
一般場景的話, 我覺得不會是從宮位找有什麼四化。
通常較多是「看XX官有沒有化祿」/「看XX官有沒有化忌」, 是明確的看官位有沒有化X(明確的X)。
如果是這樣的話看看這個是否合用:

```
//查看命宮是否同時有("化祿", "化忌")
boolean result = new DestinyCellCriteria(destiny, Temple.TEMPLE_DESTINY) //命宮
    .and()
        .sameCellStars(StarReaction.STAR_TO_TREASURE, StarReaction.STAR_TO_PROBLEM) //sameCellStars即是AND關係
    .endAnd()
    .getResult();

//查看命宮是否有任意一種("化祿","化忌")
boolean result = new DestinyCellCriteria(destiny, Temple.TEMPLE_DESTINY) //命宮
    .and()
        .sameCellSomeStars(StarReaction.STAR_TO_TREASURE, StarReaction.STAR_TO_PROBLEM) //sameCellSomeStars即是OR關係
    .endAnd()
    .getResult();
```

**Comment by airicyu** [comment]
沒有直接你說的那種查找方式。上面說的都是間接查找。

**Comment by hustxjs** [comment]
好的，明白了，谢谢！
